#!/bin/sh
set -eu

pyvers=$(py3versions -r 2>/dev/null)

cp -a tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in ${pyvers}; do
  echo "-=-=-=-=-=-=-=- running tests for ${py} -=-=-=-=-=-=-=-=-"
  printf '$ %s\n' "${py} -m pytest tests"
  ${py} -m pytest tests
done
